"use client";

import Link from "next/link";
import { ArrowLeft, ShieldCheck, Lock, Eye } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-background selection:bg-primary/20 pt-24 pb-20">
            <div className="container mx-auto px-6 max-w-4xl">
                <Link href="/">
                    <Button variant="ghost" className="mb-8 hover:bg-white/5">
                        <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
                    </Button>
                </Link>

                <div className="space-y-4 mb-12">
                    <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Privacy Policy</h1>
                    <p className="text-xl text-muted-foreground">Last Updated: January 13, 2026</p>
                </div>

                <div className="prose prose-invert max-w-none space-y-12">
                    {/* Section 1 */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold flex items-center gap-3">
                            <ShieldCheck className="h-6 w-6 text-primary" />
                            1. Our Pledge to Patient Privacy
                        </h2>
                        <p className="text-muted-foreground leading-relaxed">
                            At CareFlow, privacy is not just a compliance checkbox—it is the foundation of our clinical architecture. We understand that behind every data point is a patient under care. We engage with Protected Health Information (PHI) exclusively as a Business Associate, strictly adhering to HIPAA regulations and our Business Associate Agreements (BAA) with healthcare providers.
                        </p>
                    </section>

                    {/* Section 2 */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold flex items-center gap-3">
                            <Lock className="h-6 w-6 text-teal-400" />
                            2. Data We Process (And Data We Don't)
                        </h2>
                        <div className="grid md:grid-cols-2 gap-6 my-6">
                            <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
                                <h3 className="font-bold text-lg mb-2 text-white">We Process:</h3>
                                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground">
                                    <li>Patient identifiers (Name, MRN, Phone) for outreach.</li>
                                    <li>Clinical context provided by your EHR sync.</li>
                                    <li>Voice interactions and transcription data.</li>
                                    <li>Risk scores generated by our logic engine.</li>
                                </ul>
                            </div>
                            <div className="p-6 rounded-2xl bg-white/5 border border-white/10 opacity-75">
                                <h3 className="font-bold text-lg mb-2 text-white">We Do NOT Sell or Trade:</h3>
                                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground">
                                    <li>We never sell patient data to advertisers.</li>
                                    <li>We never trade data with third-party brokers.</li>
                                    <li>We do not use your private patient data to train public AI models.</li>
                                </ul>
                            </div>
                        </div>
                    </section>

                    {/* Section 3 */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold flex items-center gap-3">
                            <Eye className="h-6 w-6 text-blue-400" />
                            3. AI & Data Sovereignty
                        </h2>
                        <p className="text-muted-foreground leading-relaxed">
                            CareFlow utilizes state-of-the-art Large Language Models (LLMs) to power our conversational agents. However, true privacy requires sovereignty:
                        </p>
                        <ul className="space-y-3 pl-4 border-l-2 border-primary/20">
                            <li className="text-muted-foreground">
                                <strong className="text-white">Zero-Retention Inference:</strong> Voice and text data processed by our AI models are transient. They are processed for the purpose of the interaction and risk analysis, then discarded from the inference engine's memory.
                            </li>
                            <li className="text-muted-foreground">
                                <strong className="text-white">Private Instance Deployment:</strong> Whether via Vertex AI or dedicated endpoints, your data works in isolation.
                            </li>
                        </ul>
                    </section>

                    {/* Section 4 */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold">4. Your Rights</h2>
                        <p className="text-muted-foreground leading-relaxed">
                            As a Covered Entity partner using our platform, you retain full ownership of your patients' medical records. We provide full support for:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                            <li>Data access requests.</li>
                            <li>Audit log provision.</li>
                            <li>Permanent deletion of patient records upon contract termination.</li>
                        </ul>
                    </section>

                    <div className="pt-12 border-t border-white/10 text-center">
                        <p className="text-sm text-muted-foreground">
                            Questions regarding privacy? Contact our Data Protection Officer at <a href="mailto:privacy@careflow.com" className="text-primary hover:underline">privacy@careflow.com</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
